/**
 * Fonte única da lista de países (pt-BR).
 * Cobre os ~195 países soberanos atuais (membros e observadores da ONU)
 * mais Taiwan e Kosovo. Usada tanto na tabela de Países (settings) quanto
 * nos seletores de país do cadastro de parceiros.
 */
export const PAISES: string[] = [
  'Afeganistão', 'África do Sul', 'Albânia', 'Alemanha', 'Andorra', 'Angola',
  'Antígua e Barbuda', 'Arábia Saudita', 'Argélia', 'Argentina', 'Armênia',
  'Austrália', 'Áustria', 'Azerbaijão',
  'Bahamas', 'Bahrein', 'Bangladesh', 'Barbados', 'Belarus', 'Bélgica', 'Belize',
  'Benin', 'Bolívia', 'Bósnia e Herzegovina', 'Botsuana', 'Brasil', 'Brunei',
  'Bulgária', 'Burkina Faso', 'Burundi', 'Butão',
  'Cabo Verde', 'Camarões', 'Camboja', 'Canadá', 'Catar', 'Cazaquistão', 'Chade',
  'Chile', 'China', 'Chipre', 'Colômbia', 'Comores', 'Coreia do Norte',
  'Coreia do Sul', 'Costa do Marfim', 'Costa Rica', 'Croácia', 'Cuba',
  'Dinamarca', 'Djibuti', 'Dominica',
  'Egito', 'El Salvador', 'Emirados Árabes Unidos', 'Equador', 'Eritreia',
  'Eslováquia', 'Eslovênia', 'Espanha', 'Estados Unidos', 'Estônia', 'Eswatini',
  'Etiópia',
  'Fiji', 'Filipinas', 'Finlândia', 'França',
  'Gabão', 'Gâmbia', 'Gana', 'Geórgia', 'Granada', 'Grécia', 'Guatemala',
  'Guiana', 'Guiné', 'Guiné-Bissau', 'Guiné Equatorial',
  'Haiti', 'Honduras', 'Hungria',
  'Iêmen', 'Ilhas Marshall', 'Ilhas Salomão', 'Índia', 'Indonésia', 'Irã',
  'Iraque', 'Irlanda', 'Islândia', 'Israel', 'Itália',
  'Jamaica', 'Japão', 'Jordânia',
  'Kosovo', 'Kuwait',
  'Laos', 'Lesoto', 'Letônia', 'Líbano', 'Libéria', 'Líbia', 'Liechtenstein',
  'Lituânia', 'Luxemburgo',
  'Macedônia do Norte', 'Madagascar', 'Malásia', 'Malaui', 'Maldivas', 'Mali',
  'Malta', 'Marrocos', 'Maurício', 'Mauritânia', 'México', 'Mianmar',
  'Micronésia', 'Moçambique', 'Moldávia', 'Mônaco', 'Mongólia', 'Montenegro',
  'Namíbia', 'Nauru', 'Nepal', 'Nicarágua', 'Níger', 'Nigéria', 'Noruega',
  'Nova Zelândia',
  'Omã',
  'Países Baixos', 'Palau', 'Palestina', 'Panamá', 'Papua-Nova Guiné',
  'Paquistão', 'Paraguai', 'Peru', 'Polônia', 'Portugal',
  'Quênia', 'Quirguistão',
  'Reino Unido', 'República Centro-Africana', 'República Checa',
  'República Democrática do Congo', 'República do Congo', 'República Dominicana',
  'Romênia', 'Ruanda', 'Rússia',
  'Samoa', 'San Marino', 'Santa Lúcia', 'São Cristóvão e Névis',
  'São Tomé e Príncipe', 'São Vicente e Granadinas', 'Senegal', 'Serra Leoa',
  'Sérvia', 'Seychelles', 'Singapura', 'Síria', 'Somália', 'Sri Lanka', 'Sudão',
  'Sudão do Sul', 'Suécia', 'Suíça', 'Suriname',
  'Tadjiquistão', 'Tailândia', 'Taiwan', 'Tanzânia', 'Timor-Leste', 'Togo',
  'Tonga', 'Trinidad e Tobago', 'Tunísia', 'Turcomenistão', 'Turquia', 'Tuvalu',
  'Ucrânia', 'Uganda', 'Uruguai', 'Uzbequistão',
  'Vanuatu', 'Vaticano', 'Venezuela', 'Vietnã',
  'Zâmbia', 'Zimbábue',
]
